"""Add is_verified and remove is_superuser

Revision ID: 6c6bcaea3052
Revises: 85ab83b54d76
Create Date: 2026-04-22 18:14:47.362691

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "6c6bcaea3052"
down_revision: Union[str, None] = "85ab83b54d76"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "refresh_tokens",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("token_hash", sa.String(length=255), nullable=False),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.Column("is_revoked", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("last_used_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_refresh_tokens_token_hash"),
        "refresh_tokens",
        ["token_hash"],
        unique=True,
    )
    op.add_column("chunks", sa.Column("text", sa.Text(), nullable=False))
    op.add_column("chunks", sa.Column("token_count", sa.Integer(), nullable=False))
    op.add_column("chunks", sa.Column("page_number", sa.Integer(), nullable=True))
    op.add_column("chunks", sa.Column("start_time", sa.Float(), nullable=True))
    op.add_column("chunks", sa.Column("end_time", sa.Float(), nullable=True))
    op.add_column("chunks", sa.Column("embedding_id", sa.Integer(), nullable=True))
    op.drop_column("chunks", "vector_id")
    op.drop_column("chunks", "content")
    op.drop_column("chunks", "index_in_file")
    op.add_column("files", sa.Column("user_id", sa.Uuid(), nullable=False))
    op.add_column(
        "files", sa.Column("original_filename", sa.String(length=255), nullable=False)
    )
    op.add_column(
        "files", sa.Column("storage_path", sa.String(length=512), nullable=False)
    )
    op.add_column("files", sa.Column("file_size", sa.Integer(), nullable=False))
    op.drop_constraint(op.f("files_owner_id_fkey"), "files", type_="foreignkey")
    op.create_foreign_key(
        None, "files", "users", ["user_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_column("files", "file_path")
    op.drop_column("files", "owner_id")
    op.add_column(
        "transcript_segments", sa.Column("confidence", sa.Float(), nullable=False)
    )
    op.add_column("users", sa.Column("is_verified", sa.Boolean(), nullable=False))
    op.drop_column("users", "is_superuser")
    op.drop_column("users", "full_name")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "full_name", sa.VARCHAR(length=255), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "users",
        sa.Column("is_superuser", sa.BOOLEAN(), autoincrement=False, nullable=False),
    )
    op.drop_column("users", "is_verified")
    op.drop_column("transcript_segments", "confidence")
    op.add_column(
        "files", sa.Column("owner_id", sa.UUID(), autoincrement=False, nullable=False)
    )
    op.add_column(
        "files",
        sa.Column(
            "file_path", sa.VARCHAR(length=512), autoincrement=False, nullable=False
        ),
    )
    op.drop_constraint(None, "files", type_="foreignkey")
    op.create_foreign_key(
        op.f("files_owner_id_fkey"),
        "files",
        "users",
        ["owner_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_column("files", "file_size")
    op.drop_column("files", "storage_path")
    op.drop_column("files", "original_filename")
    op.drop_column("files", "user_id")
    op.add_column(
        "chunks",
        sa.Column("index_in_file", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "chunks", sa.Column("content", sa.TEXT(), autoincrement=False, nullable=False)
    )
    op.add_column(
        "chunks",
        sa.Column(
            "vector_id", sa.VARCHAR(length=255), autoincrement=False, nullable=True
        ),
    )
    op.drop_column("chunks", "embedding_id")
    op.drop_column("chunks", "end_time")
    op.drop_column("chunks", "start_time")
    op.drop_column("chunks", "page_number")
    op.drop_column("chunks", "token_count")
    op.drop_column("chunks", "text")
    op.drop_index(op.f("ix_refresh_tokens_token_hash"), table_name="refresh_tokens")
    op.drop_table("refresh_tokens")
    # ### end Alembic commands ###
